---
title: "Untitled"
editor: visual
format: docx # setzt das Format des Outputs
fig-width: 6.56 # setzt 6.56 Zoll als Standard-Breite für alle Plot-Outputs
fig-dpi: 300 # setzt alle plots auf 300 dpi
execute:
  warning: false
  message: false
  echo: false
---

```{r setup}
library(tidyverse)

df <- palmerpenguins::penguins

my_theme <-  theme_light(base_family = 'Helvetical',
              base_size = 10) +
  theme(legend.position = 'bottom')

theme_set(my_theme)
```

Meine beeindruckend schöne Grafik ist in @fig-scatter zu sehen.

```{r graph}
#| label: fig-scatter
#| fig-cap: Verteilungen der Schnabellänge und Körpergewichte der beobachteten Pinguine, aufgeteilt nach der Insel auf der die Pinguine beobachtet wurden und der Spezies der Pinguine.


penguin_means <- palmerpenguins::penguins %>% 
  group_by(species, island) %>% 
  summarise(across(c(bill_length_mm, body_mass_g), ~mean(., na.rm=T)))

df %>% 
  ggplot(aes(x = bill_length_mm, 
             y = body_mass_g,
             color = species)) + 
  geom_point(aes(shape = 'Original'),
             alpha = .5) +
  geom_point(data=penguin_means,
             aes(shape = 'Mittelwert'),
             size = 3) +
  scale_color_viridis_d(end = 0.7) +
  scale_shape_manual(values = c(Original = 20, Mittelwert = 3))+
  coord_fixed(ratio = 10/1000) +
  facet_wrap(~island) +
  labs(x = 'Schnabellänge (mm)',
       y = 'Körpergewicht (g)',
       color = 'Pinguin-Spezies',
       shape = 'Aggregations-Niveau')+
  theme(legend.title = element_text(size = 10,
                                    colour = 'darkgrey'))+
  guides(color = guide_legend(nrow = 3),
         shape = guide_legend(nrow = 2))
```

In dem Datensatz wurden N=`r sum(!is.na(palmerpenguins::penguins$sex))` Pinguine untersucht, davon `r sum(palmerpenguins::penguins$sex == 'male', na.rm = T)` männliche und `r sum(palmerpenguins::penguins$sex == 'female', na.rm = T)` weibliche Exemplare.